### PR TITLE
Update porkbun hostname

### PR DESCRIPTION
**Pull request by danielkinahan**
Addresses #9

### CODE REVIEW

**Comment by Niallfitzy1** [comment]
Thanks for opening the PR, I'll merge& release this tomorrow

**Comment by Pranta2020** [comment]
> Thanks for opening the PR, I'll merge& release this tomorrow

Is there a specific release date?

**Comment by bdr99** [comment]
Can a new release be published with this change included?

**Comment by Niallfitzy1** [comment]
`github.com/libdns/porkbun@v0.2.0` & `github.com/caddy-dns/porkbun@v0.2.0` have been published with the hostname changes.

**Pull request merged**
